# Generated by Django 4.1 on 2022-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('name_lower', models.CharField(max_length=255)),
                ('current_price', models.IntegerField()),
                ('before_discount', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-shop'],
            },
        ),
    ]
