# Generated by Django 4.1 on 2022-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_phones_before_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='before_discount',
            field=models.IntegerField(null=True),
        ),
    ]
